# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false

    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    assets:
        packages:
            css:
                base_path: assets/css/
            fonts:
                base_path: assets/fonts/
            js:
                base_path: assets/js/
            favicon:
                base_path: assets/favicon/

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
