extends: "default"

ignore: |
  build/
  var/
  vendor/

rules:
  comments:
    min-spaces-from-content: 1
  document-end: disable
  document-start: disable
  line-length:
    max: 120
  truthy:
    allowed-values: ['true', 'false', 'on']

yaml-files:
  - "yamllint.config.yaml"
  - "*.yaml"
  - "*.yml"
